apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-on-kubernetes-mysql-pvc
  namespace: ghost-on-kubernetes
  labels:
    app: ghost-on-kubernetes-mysql
    app.kubernetes.io/name: ghost-on-kubernetes-mysql-pvc
    app.kubernetes.io/instance: ghost-on-kubernetes
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: database-storage
    app.kubernetes.io/part-of: ghost-on-kubernetes
    
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
