apiVersion: v1
kind: Secret
metadata:
  name: ghost-config-prod
  namespace: ghost-on-kubernetes
  labels:
    app: ghost-on-kubernetes
    app.kubernetes.io/name: ghost-config-prod
    app.kubernetes.io/instance: ghost-on-kubernetes
    app.kubernetes.io/version: '5.92'
    app.kubernetes.io/component: ghost-config
    app.kubernetes.io/part-of: ghost-on-kubernetes
type: Opaque
stringData:
  config.production.json: |-
    {
      "url": "https://phuongdt.com",
      "admin": {
        "url": "https://phuongdt.com"
      },
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "logging": {
        "transports": [
          "stdout"
        ]
      },
      "database": {
        "client": "mysql",
        "connection": 
        {
          "host": "ghost-on-kubernetes-mysql-service",
          "user": "mysql-db-user",
          "password": "fky7xgc_ZQM7whd7zne",
          "database": "mysql-db-phuongdt",
          "port": "3306"
        }
      },
      "process": "local",
      "paths": {
        "contentPath": "/home/nonroot/app/ghost/content"
      }
    }
